<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		D:
		/CoolTutor
		/Ampps
		/www
		/claro
		/claroline
		/inc
		/lib
		/config.class.php
 * Date November 28, 2016 at 07:21 PM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLANNGenDate is an internal mark
   $CLANNGenDate = "1480360909";

/* announcementPortletMaxItems : Use 0 to display all */
$GLOBALS['announcementPortletMaxItems'] = 3;



?>