<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		D:
		/CoolTutor
		/Ampps
		/www
		/claro
		/claroline
		/inc
		/lib
		/config.class.php
 * Date November 28, 2016 at 07:21 PM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLHOMEGenDate is an internal mark
   $CLHOMEGenDate = "1480360909";

/* course_order_by : Order course by */
$GLOBALS['course_order_by'] = 'official_code';


/* categories_order_by : Order categories by */
$GLOBALS['categories_order_by'] = 'rank';


/* course_categories_hidden_to_anonymous : Hide course categories to anonymous */
$GLOBALS['course_categories_hidden_to_anonymous'] = FALSE;


/* userCourseListGroupByCategories : Group user courses by categories */
$GLOBALS['userCourseListGroupByCategories'] = FALSE;


/* display_former_homepage : Display former Claroline's home page instead of user's desktop */
$GLOBALS['display_former_homepage'] = FALSE;


/* userDesktopMessageCollapsedByDefault : Hide textzone on user desktop by default */
$GLOBALS['userDesktopMessageCollapsedByDefault'] = TRUE;



?>