<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		D:
		/CoolTutor
		/Ampps
		/www
		/claro
		/claroline
		/inc
		/lib
		/config.class.php
 * Date November 28, 2016 at 07:21 PM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLKCACHEGenDate is an internal mark
   $CLKCACHEGenDate = "1480360909";

/* cache_lifeTime : Time to keep a cache as valid */
$GLOBALS['cache_lifeTime'] = 10;


/* cache_automaticCleaningFactor : write n-1 times without check if (others) cached files are or not deprecated */
$GLOBALS['cache_automaticCleaningFactor'] = 40;



?>