<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		D:
		/CoolTutor
		/Ampps
		/www
		/claro
		/claroline
		/inc
		/lib
		/config.class.php
 * Date November 28, 2016 at 07:21 PM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLMSGGenDate is an internal mark
   $CLMSGGenDate = "1480360909";

/* messagePerPage : Number of message per page */
$GLOBALS['messagePerPage'] = 15;


/* mailNotification : Enable Email notification */
$GLOBALS['mailNotification'] = TRUE;


/* userCanSendMessage : Users can send messages from outside a course context */
$GLOBALS['userCanSendMessage'] = FALSE;



?>