<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		
		D:
		/CoolTutor
		/Ampps
		/www
		/claro
		/claroline
		/inc
		/lib
		/config.class.php
 * Date November 28, 2016 at 07:21 PM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLWIKIGenDate is an internal mark
   $CLWIKIGenDate = "1480360909";

/* showWikiEditorToolbar : Show wiki syntax toolbar */
$GLOBALS['showWikiEditorToolbar'] = TRUE;


/* forcePreviewBeforeSaving : Force text preview before saving it */
$GLOBALS['forcePreviewBeforeSaving'] = FALSE;



?>